name: "Test"

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request: {}
  push:
    branches:
    - master
    - test-coverage
  schedule:
  - cron: '0 0 * * *'  # every day at midnight, to test against nightlies

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        kongVersion:
        - "2.8.x"
        - "3.0.x"
        - "dev"

    steps:
    - uses: actions/checkout@v3

    - uses: Kong/kong-pongo-action@v1
      with:
        pongo_version: master
        kong_version: ${{ matrix.kongVersion }}
        # Non-Kong-Inc users should provide their Enterprise license as a secret
        # if testing against Enterprise versions.
        # Kong Inc users should use the `Kong/kong-license` action
        # license: ${{ secrets.KONG_LICENSE_DATA }}

    - run: pongo run -- --coverage
    - uses: coverallsapp/github-action@v2
      continue-on-error: true
      with:
        debug: true